### ISSUE TITLE
no default parameters in tractography palette for DTI scheme

### ISSUE THREAD

**Issue by agriffa** [LTS5/cmp#102]
When you select imaging modality: DTI and you want to perform tractography, no default values appear in the 'tractography page' of the cmp GUI. 
I have also the impression that they are not well defined in tractography.py (comparing fiber_tracking_dsi() and fiber_tracking_dti() and fiber_tracking_qball())

**Comment by unidesigner** [comment]
Just fixed it in current master. Please check.

**Comment by agriffa** [comment]
Yes, perfect, thanks

**Comment by unidesigner** [comment]
ok. i close this issue.
