### ISSUE TITLE
Bug running 'Apply Registration'?

### ISSUE THREAD

**Issue by agriffa** [LTS5/cmp#103]
When I try to run 'Apply Registration' I get the error:

Stage 'cmp.stages.registration.apply_registration' missing input, file not found: /home/agriffa/DATA_TEST_pipeline/dataset_test_pipeline/connectome_0001/tp1/CMP/fs_output/HR/freesurferaparc/ROI_HR_th.nii.gz

My freesurferaparc is in fact empty (note that I run the registration -non linear-, segmentation and registration before). Is it possible that files in freesurferaparc are created and then deleted at a certain point?

**Comment by unidesigner** [comment]
have you run parcellation?

**Comment by agriffa** [comment]
yes, the Lausanne2008 one

**Comment by unidesigner** [comment]
Ok. I think I know the problem. If you have selected Lausanne2008 (the multi-resolution parcellation), there are no freesurferaparc files (they are generated if you would have selected NativeFreesurfer). Depending on what you have generated last, you should be able to run apply registration (make sure that the selection in the parcellation tab is correct).

**Comment by agriffa** [comment]
Ok, thanks! In fact now it works.
So, to run independently the different stages the right way is to select also the previous steps and 'Skip Previously Completed Stage' such to re-define the variables, right?

**Comment by unidesigner** [comment]
This is one way to do it I think. I always select only the stage to run (but having the variables still correctly set in the other stages where necessary)

**Comment by unidesigner** [comment]
I close this issue for now.
