### ISSUE TITLE
q-ball reconstruction

### ISSUE THREAD

**Issue by agriffa** [LTS5/cmp#112]
Concerning the Diffusion Toolkit commands for q-ball reconstruction:

1: hardi_mat
    Example:
        hardi_mat "/home/cmt/cmtk/LTS5-cmp-7dbfbd5/cmp/data/diffusion/gradient_tables/siemens_256.txt" "/home/cmt//Diffusion_data/S01/QBI/NIFTI/temp_mat.dat -ref "/home/cmt/Diffusion_data/S01/QBI/CMP/raw_diffusion/QBALL_resampled_2x2x2.nii.gz" -oc

```
According to the DTK documentation, -ref is not an option for hardi_mat, and -oc has no meaning if the -iop option (image orientation patient) is not specified. So we can discard them.
```

2: odf_recon
    Example: 
        odf_recon "/home/cmt/Diffusion_data/S01/QBI/CMP/raw_diffusion/2x2x2/MR0000.nii.gz" 257 181 "/home/cmt/Diffusion_data/S01/QBI/CMP/raw_diffusion/qball_0/hardi_" -mat "/home/cmt/Diffusion_data/S01/QBI/NIFTI/temp_mat.dat" -s 0 -b0 1 -p 3 -sn 1 -ot nii

```
-sn (start number of the input filename numbering) must be set to 0, otherwise the reconstruction does not complete correctly.
```

**Comment by unidesigner** [comment]
I checked hardi_mat --help, and it has options -ref and -oc. Do you think the results are wrong like this, i.e. should we remove them as the default?

for the -sn 1, I will set the default to 0, but of course it can be changed from the GUI.

**Comment by agriffa** [comment]
Ok, it seems that they should complete the DTK web page documentation with the command line one, and vice versa ;)
For the -oc they say on the web: 'when this flag in on, '-iop' information must also be given', but in fact it does not complain.
Anyway, it seems to me that the results are the same, with and without -ref and -oc, but let me verify.

Yes, you can change -sn from the GUI, but in principle it will be always 0 as it refers to the list of images in output from fsl_split (dtk.py), isn't it?

**Comment by unidesigner** [comment]
ok, i would rather trust the cmdline help in such cases. for the -oc, it does not say it needs -iop.

I changed to 0 as default.

**Comment by unidesigner** [comment]
could you already check if i can remove the -ref -oc flags without an effect on the result?

**Comment by unidesigner** [comment]
as the output command line is produced by the current diffusion toolkit version as it is, i keep it like that and close this issue.
