### ISSUE TITLE
q-ball tracking

### ISSUE THREAD

**Issue by agriffa** [LTS5/cmp#115]
Getting the error 

AttributeError: 'CMPGUI' object has no attribute 'streamline_param_dti'

refered to line 

File "/home/cmt/Dev/packages/cmp/stages/tractography/tractography.py", line 156, in fiber_tracking_qball
    if not gconf.streamline_param_dti == ''

when trying to run tractography for QBALL dataset from the GUI

**Comment by unidesigner** [comment]
this is fixed in master and should be release in 1.0.3

**Comment by agriffa** [comment]
right, thanks
