### ISSUE TITLE
parecellation 1015

### ISSUE THREAD

**Issue by agriffa** [LTS5/cmp#125]
We need to remember we have to verify twonodes in the parcellation Lausanne2008, resolution 1015:
- nodes 707 and 711 corresponds both to the ROI name isthmuscingulate_4
- nodes 853 and 869 corresponds both to the ROI name lateraloccipital_1

**Comment by unidesigner** [comment]
I checked in the file ParcellationLausanne2008.xls and I think this are typos.
For lateraloccipital on sheet "left", there are two lateraloccipital_1, but lateraloccipital_21 is missing (lateraloccipital_22/23 exists).
Same for isthmuscingulate_4, they are duplicated on the excel sheet, but isthmuscingulate_5 is missing.
To solve this, we could just replace one isthmuscingulate_4 by isthmuscingulate_5 and one lateraloccipital_1 by lateraloccipital_21.

To be sure to know which one to select for the renaming, we might have to check back with Leila.

Can you check if lateraloccipital_21 and isthmuscingulate_5 are generated in a processed subject for in the FREESURFER/labels folder?

**Comment by agriffa** [comment]
Yes, it was what I was thinking. I can write again to Leila.

Yes, ateraloccipital_21 and isthmuscingulate_5 (lh) are generated in FREESURFER/labels folder.
