### ISSUE TITLE
freesurfer progress

### ISSUE THREAD

**Issue by unidesigner** [LTS5/cmp#52]
and parts of it running only for wm mask correction / inspection:

it is at the end of the step2 that you need to check and corrected if needed the wm.mgz (white matter volume) and and relaunched the the second step.

Commande for visualisation :
 tkmedit <subjectID> wm.mgz lh.pial -aux T1.mgz -aux-surface rh.pial (this will load the white matter volume with the each surface per hemisphere and the T1.mgz volume which is needed for the correction)

Commande to relaunch the second step with the wm.mgz corrected:

recon-all -autorecon2-wm -s <subjectID>  (recreate a new white matter surface with the correction made)

There is few other check to do be the same way may be it is better to have a appointment for me to show you what is needed.

after all the corrections on surfaces,  we'll still need to go through the final step: recon-all -autorecon3 -s <subjectID>  (I see now that this step is essential as it creates the aseg.mgz volume (contains the subcortical structure segmentation)

**Comment by unidesigner** [comment]
http://surfer.nmr.mgh.harvard.edu/fswiki/ReconAllDevTable

**Comment by unidesigner** [comment]
where is wm.mgz actually used inside our pipeline? (ale?)
is it the basis for the ribbon?

**Comment by unidesigner** [comment]
right now, the pipeline uses this command after the wm correction:
recon-all -s FREESURFER -autorecon2-wm -autorecon3 -no-isrunning

**Comment by Marie-Christine** [comment]
after having redone the white matter surface, it is important to check if the pial surface (external cortical surface) is not including parts of the membrane.

It can be something to think about as after correcting the 2 surfaces you can extract accurate values of cortical thickness and volumes as well as your connectome data. !!!
(I think it can give a plus to this programme

**Comment by unidesigner** [comment]
hi there. you are actually the first person that enters here something other than myself :) welcome!

**Comment by Marie-Christine** [comment]
=) try to help as I can... :p

Searching now the answer for your second comment... I think yes but I want to be sure of that before saying any silly things.

**Comment by Marie-Christine** [comment]
The ribbon is created by freesurfer using the 2 surfaces the white matter and the pial and the aseg.mgz volume. (cf ReconAllDevTable)
As the white matter surface is created directly from the white matter volume (wm.mgz), correcting the wm.mgz of defects will have a direct impact on the results of connectome.
It confims as well the need to correct the pial surface as it is a direct component of the ribbon creation.

**Comment by unidesigner** [comment]
Is the ribbon volume really created by these 2 surfaces. Isn't it the other way round? I.e. the surfaces are created by the ribbon, which was segmented white and grey matter?
One problem with the pipeline right know is, that the ROI_HR_th.nii files for the ROIs has many voxel inside white matter, and has also many "wholes" (i.e. non-contigious) which lead to fiber loss. See also Issue 64.

**Comment by Marie-Christine** [comment]
This is a general question about how Freesurfer works. First the program correct and normalize the raw images.
Second, it segment the volume for extracting the white matter volume only. 
Third, on this volume it creates the first surface, which is the white matter surface (yellow) see the following :http://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferAnalysisPipelineOverview
Then it is creating the pial surface (red) with a "growing" algorithm until the surface reaches the end of the cortex.
The ribbon is the results of the space that exists between these 2 surfaces.

**Comment by Marie-Christine** [comment]
As I understood, the ribbon is converted from a space between 2 surfaces (3D vertex) to a volume (voxel) and this conversion creates the "holes"... This is what I understood. May be it need a confirmation from an other member of this group.
Does it make any sense ?

**Comment by unidesigner** [comment]
probably needs investigation of people who work on the segmentation part.
