### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by agriffa** [LTS5/cmp#94]
What about saving into different log files the various pipeline steps' logs, even if the steps are executed all-at-once? Now the log file is really long and difficult to read.

**Comment by daducci** [comment]
One suggestion could be to have all the modules writing into different streams (stdout and stderr basically), and then create one log file for each. This way, if you want to se if everything was fine, you would just need to check the log for the stderr stream

**Comment by unidesigner** [comment]
not pipeline execution should usually throw and exception and stop if there was an error. so the error should be displayed at the end of the log file and in the log window.
